# Generated by Django 3.2.16 on 2023-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_names_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('planet', models.CharField(max_length=20)),
                ('element', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
            ],
        ),
    ]
