# Generated by Django 3.2.16 on 2023-01-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_accountholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='currencies_visited',
        ),
    ]
