# Generated by Django 3.2.16 on 2023-01-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_city_compatiblehoroscope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compatiblehoroscope',
            old_name='horoscope',
            new_name='horoscope1',
        ),
    ]
