# Generated by Django 3.2.16 on 2023-01-21 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_horoscope_compatiblehoroscope_horoscope1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
