# Generated by Django 3.2.16 on 2023-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_rates_x_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='instagram',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
    ]
